apiVersion: v1
kind: Service
metadata:
  name: greetings-k8s
  namespace: 01-hello-world
spec:
  selector:
    app: greetings-k8s
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer