apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-k8s
  namespace: lab-07
  labels:
    app: greetings-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greetings-k8s
  template:
    metadata:
      labels:
        app: greetings-k8s
    spec:
      containers:
      - name: greetings-k8s-container
        image: greetings-api:v6
        imagePullPolicy: IfNotPresent
        env:
          - name: password
            valueFrom:
              secretKeyRef:
                name: greetings-k8s
                key: password
        ports:
        - containerPort: 3000