# External Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: greetings-k8s 
  namespace: lab-07
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager # Secret Store name
    kind: SecretStore
  target:
    name: greetings-k8s # Generate Secret name
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: passkey # AWS Secrets Manager Secret Name
        # property: password