apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-k8s
  namespace: lab-06
  labels:
    app: greetings-k8s
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greetings-k8s
  template:
    metadata:
      labels:
        app: greetings-k8s
    spec:
      containers:
      - name: greetings-k8s-container
        image: greetings-api:v5
        env:
          - name: NAME
            valueFrom:
              configMapKeyRef:
                name: greetings-k8s
                key: name
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000



# Ler parte de secrets
# Ler parte de estado do terraform

