apiVersion: v1
kind: Service
metadata:
  name: cloud-app
  namespace: lab-04
spec:
  selector:
    app: cloud-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer