# Secret Store
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: lab-07
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1